name: CI/CD

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AZURE_CORE_OUTPUT: none
  AZURE_WEBAPP_PACKAGE_PATH: "./app.zip"
  DOTNET_VERSION: "9.0.x"

jobs:
  build_test_publish:
    name: Build, execute tests and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build
        run: dotnet build . 
      - name: Publish
        run: dotnet publish . --output ./temp
      - name: Create Zip
        shell: pwsh
        run: |
          cd ./temp
          zip -r ../app.zip ./*
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hu
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    environment: dev
    needs: [build_test_publish]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          inlineScript: |
            az account show
      - name: Check
        uses: azure/cli@v2
        with:
          inlineScript: |
            echo $(az account show)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: customerReproTest
          resource-group-name: webapps-deploy-test
          package: .
      # - name: Deploy to Azure Web App
      #   uses: azure/cli@v2
      #   with:
      #     inlineScript: |
      #       az webapp deploy --resource-group kv-secret-rotation-sample-rg-dev --name kv-secret-rotation-sample-appsrv-dev --src-path $GITHUB_WORKSPACE/arbitrary-aspnetcore-webapi/app.zip --track-status false
      - name: Logout
        run: |
          az logout
